ALFREDAPI-504 Draft PR Dynamic Extensions --> Alfresco MVC
xenit-eu/alfred-api pull request #146
Opened 2022-10-25 19:50 UTC by todorinskiz

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-<**YOUR TICKET ID**>

- [ ] Is [CHANGELOG.md](https://github.com/xenit-eu/alfred-api/blob/master/CHANGELOG.md) extended?
- [ ] Does this PR avoid breaking the API? 
    Breaking changes include adding, changing or removing endpoints and/or JSON objects used in requests and responses.
- [ ] Does the PR comply to REST HTTP result codes policy outlined in the [user guide](https://docs.xenit.eu/alfred-api/stable-user/rest-api/index.html#rest-http-result-codes)?
- [ ] Is error handling done through a method annotated with `@ExceptionHandler` in the webscript classes?
- [ ] Does the PR follow our [coding styleguide and other active procedures](https://xenitsupport.jira.com/wiki/spaces/XEN/pages/624558081/XeniT+Enhancement+Proposals+XEP)?
- [ ] Is usage of `this.` prefix avoided?

See [README.md](./README.md) for full explanation.

2022-10-31 13:08 UTC, todorinskiz commented
First successful build after flaky tests: https://jenkins-2.xenit.eu/job/Xenit%20Github/job/alfred-api/job/ALFREDAPI-504/

2022-11-16 14:15 UTC, WimCrols commented
Until we decide to go forth with this, I would like to merge this PR not into `master`, but another longliving branch e.g. `master-mvc`.

2022-11-16 15:15 UTC, WimCrols commented
It's not yet clear to me why the `alfresco` dir was add in e.g. apix-integration-tests/alfresco/src/main/ ?

2022-11-17 10:44 UTC, WimCrols commented
Please remove gradle.bat (it's empty)

2022-11-17 10:44 UTC, WimCrols commented
Is the temp_dependencies folder here because you wait on the next alfrsco-mvc release?

2022-11-17 12:24 UTC, WimCrols requested changes

2022-11-17 12:47 UTC, todorinskiz commented on apix-docker/70/docker-compose.yml
> -  activemq:
They are unnecessary in Alfresco 7, all we need is a local transformer so Solr can keep indexing on content

2022-11-17 12:48 UTC, todorinskiz commented on apix-rest-v1/src/main/java/eu/xenit/apix/rest/AlfredApiRestServletContext.java
> +//import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
Indeed, after the decision to export OpenAPI + Swagger UI in an external component, this can be removed.

2022-11-17 12:49 UTC, todorinskiz commented on apix-rest-v1/build.gradle
> +//    implementation "org.springframework.boot:spring-boot-starter-parent:2.6.6"
Will do!

2022-11-17 12:50 UTC, todorinskiz commented on apix-integrationtests/alfresco/src/main/java/eu/xenit/apix/tests/search/SearchServiceFacetsTest.java
> -    @Override
It was not used (grayed out). Qualifying for removal?

2022-11-17 12:51 UTC, todorinskiz commented on apix-impl/build.gradle
> -plugins {
By accident :) to be removed

2022-11-17 12:58 UTC, todorinskiz commented on apix-docker/72/docker-compose.yml
> +      - "${DOCKER_IP}:8080:8080"
That was meant for local development, I should revert it

2022-11-17 13:00 UTC, todorinskiz commented
> It's not yet clear to me why the `alfresco` dir was added in e.g. apix-integration-tests/alfresco/src/main/ ?

To isolate it in its own context, because of the configuration of the subprojects:
https://github.com/xenit-eu/alfred-api/blob/ALFREDAPI-504/apix-integrationtests/alfresco/build.gradle#L66

2022-11-17 13:13 UTC, WimCrols commented on apix-integrationtests/alfresco/src/main/java/eu/xenit/apix/tests/search/SearchServiceFacetsTest.java
> -    @Override
If you're sure... Just don't trust IntelliJ completely. Alfrd API mostly works in it, but not 100%. 
If this does not show up in past tests, feel free to remove.

2022-11-17 13:14 UTC, WimCrols commented
> > It's not yet clear to me why the `alfresco` dir was added in e.g. apix-integration-tests/alfresco/src/main/ ?
> 
> To isolate it in its own context, because of the configuration of the subprojects: https://github.com/xenit-eu/alfred-api/blob/ALFREDAPI-504/apix-integrationtests/alfresco/build.gradle#L66

Aha, ok I see.

2022-11-30 15:10 UTC, todorinskiz commented
> Please remove gradle.bat (it's empty)
It has content?

2022-12-14 14:35 UTC, todorinskiz commented
> > 
> 
> Well, I see ![image](https://user-images.githubusercontent.com/16096822/204843977-701e8bff-f55c-494d-8a8a-5a3870570735.png) But if for some reason that's a bug, please ignore my remark.

That's making the wrapper executable :)

2022-12-14 14:59 UTC, WimCrols commented
Ok, considere the gradlew.bat remark resolved.

2023-02-02 10:10 UTC, WimCrols approved these changes
:shipit:

2023-02-02 15:47 UTC, merged