ALFREDAPI-556 [Update] package name-change from 'eu.xenit.apix' to 'e…
xenit-eu/alfred-api pull request #223
Opened 2024-08-12 09:07 UTC by codingBenVdS

ALFREDAPI-556 [Update] package name-change from 'eu.xenit.apix' to 'eu.xenit.alfred.api'

Fixes https://xenitsupport.jira.com/browse/ALFREDAPI-556

- [ ] Is [CHANGELOG.md](https://github.com/xenit-eu/alfred-api/blob/master/CHANGELOG.md) extended?
- [ ] Does this PR avoid breaking the API? 
    Breaking changes include adding, changing or removing endpoints and/or JSON objects used in requests and responses.
- [ ] Does the PR comply to REST HTTP result codes policy outlined in the [user guide](https://docs.xenit.eu/alfred-api/user/rest-api/index.html#rest-http-result-codes)?
- [ ] Is error handling done through a method annotated with `@ExceptionHandler` in the webscript classes?
- [ ] Does the PR follow our [coding styleguide and other active procedures](https://xenitsupport.jira.com/wiki/spaces/XEN/pages/624558081/XeniT+Enhancement+Proposals+XEP)?
- [ ] Is usage of `this.` prefix avoided?

See [README.md](./README.md) for full explanation.

2024-08-12 10:41 UTC, todorinskiz commented on apix-impl/src/main/java/eu/xenit/alfred/api/Version.java
> +package eu.xenit.alfred.api;
I'm not really happy with this file. Can't we use reflection?

```
YourClass.class.getPackage().getSpecificationVersion();
```

2024-08-12 10:42 UTC, todorinskiz reviewed
minor remark

2024-08-12 10:48 UTC, todorinskiz commented
How far are we willing to go here?
There is still:

- test model with `apix`
- URL path starts with `/apix/...`
- gradle projects are also `apix-...`

2024-08-12 11:29 UTC, WimCrols commented
> How far are we willing to go here? There is still:
> 
> * test model with `apix`
> * URL path starts with `/apix/...`
> * gradle projects are also `apix-...`

True... you to stop somewhere. I'm open to adjusting internal names, but URL I would not touch. Maybe out of scope for this ticket.

We also may need to doublecheck artifact names...

Also

2024-08-12 11:30 UTC, WimCrols requested changes

2024-08-12 11:52 UTC, WimCrols commented on apix-impl/src/main/java/eu/xenit/alfred/api/Version.java
How did you manage to get this committed? It's ignored in https://github.com/xenit-eu/alfred-api/blob/master/.gitignore#L2

2024-08-12 11:53 UTC, WimCrols commented on apix-impl/src/main/java/eu/xenit/alfred/api/Version.java
Ah, I see... the path has changed and needs to be adjusted.

2024-08-12 12:54 UTC, codingBenVdS commented on apix-impl/src/main/java/eu/xenit/alfred/api/Version.java
i looked over this. I'll adjust whats necessary

2024-08-12 12:56 UTC, RVanhuysseXenit commented
> How far are we willing to go here? There is still:
> 
>     * test model with `apix`
> 
>     * URL path starts with `/apix/...`
> 
>     * gradle projects are also `apix-...`

For this particular issue i was just hoping for package names. There's 2 reasons:
* code generation becomes easier. without this change there's still some manual/bulk fiddling to align the interface object with generated obejcts
* you avoid confusion for devs that use the interface as a lib for their client, pdl had issues with this. Having to explain the old situation created some friction. With a less easygiong client this would have been a big issue.

2024-08-12 12:58 UTC, codingBenVdS commented on apix-interface/src/main/java/eu/xenit/apix/dictionary/properties/IPropertyService.java
that's correct.
![image](https://github.com/user-attachments/assets/94afcd88-4bed-41d8-ba2e-b1793c782ae8)

2024-08-12 13:07 UTC, codingBenVdS commented on apix-impl/src/main/java/eu/xenit/alfred/api/Version.java
Removed the file and updated .gitignore

2024-08-13 09:45 UTC, codingBenVdS commented
Changed all the apix references from the (Folders || Classnames || Variables || ..)

2024-08-13 09:57 UTC, WimCrols approved these changes

2024-08-13 10:50 UTC, todorinskiz approved these changes

2024-08-13 11:09 UTC, merged